// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddProductToCartInput struct {
	CartID    string `json:"cartId"`
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type Cart struct {
	ID        string         `json:"id"`
	IsActive  bool           `json:"isActive"`
	Value     float64        `json:"value"`
	User      *User          `json:"user"`
	UserID    *string        `json:"userId,omitempty"`
	Order     *Order         `json:"order,omitempty"`
	Products  []*CartProduct `json:"products,omitempty"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type CartProduct struct {
	ID        string    `json:"id"`
	Quantity  int       `json:"quantity"`
	Product   *Product  `json:"product"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Category struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Products []*Product `json:"products,omitempty"`
}

type CreateCartInput struct {
	IsActive bool    `json:"isActive"`
	Value    float64 `json:"value"`
	UserID   string  `json:"userId"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateOrderInput struct {
	Value  float64 `json:"value"`
	CartID string  `json:"cartId"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Description *string `json:"description,omitempty"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ListProductsInput struct {
	Name  *string        `json:"name,omitempty"`
	Price *float64       `json:"price,omitempty"`
	Order *string        `json:"order,omitempty"`
	Sort  *SortDirection `json:"sort,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Order struct {
	ID            string         `json:"id"`
	Value         float64        `json:"value"`
	PaymentStatus *PaymentStatus `json:"paymentStatus,omitempty"`
	BillingType   *BillingType   `json:"billingType,omitempty"`
	Cart          *Cart          `json:"cart"`
	User          *User          `json:"user"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Price       float64   `json:"price"`
	Description *string   `json:"description,omitempty"`
	CategoryID  *string   `json:"categoryID,omitempty"`
	Category    *Category `json:"category,omitempty"`
	Carts       []*Cart   `json:"carts,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type UpdateCategoryInput struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

type UpdateProductInput struct {
	ID          string   `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type UpdateUserInput struct {
	ID              string  `json:"id"`
	Name            *string `json:"name,omitempty"`
	Email           *string `json:"email,omitempty"`
	NewPassword     *string `json:"newPassword,omitempty"`
	ConfirmPassword string  `json:"confirmPassword"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Cart      []*Cart   `json:"cart,omitempty"`
	Orders    []*Order  `json:"orders,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type BillingType string

const (
	BillingTypeBoleto     BillingType = "BOLETO"
	BillingTypePix        BillingType = "PIX"
	BillingTypeCreditCard BillingType = "CREDIT_CARD"
	BillingTypeDebitCard  BillingType = "DEBIT_CARD"
)

var AllBillingType = []BillingType{
	BillingTypeBoleto,
	BillingTypePix,
	BillingTypeCreditCard,
	BillingTypeDebitCard,
}

func (e BillingType) IsValid() bool {
	switch e {
	case BillingTypeBoleto, BillingTypePix, BillingTypeCreditCard, BillingTypeDebitCard:
		return true
	}
	return false
}

func (e BillingType) String() string {
	return string(e)
}

func (e *BillingType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BillingType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BillingType", str)
	}
	return nil
}

func (e BillingType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "PENDING"
	PaymentStatusConfirmed PaymentStatus = "CONFIRMED"
	PaymentStatusOverdue   PaymentStatus = "OVERDUE"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusPending,
	PaymentStatusConfirmed,
	PaymentStatusOverdue,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusPending, PaymentStatusConfirmed, PaymentStatusOverdue:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
