package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/lucasshuan/b2c-ecommerce-api/internal/gql"
)

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input gql.ChangePasswordInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}

// SignIn is the resolver for the signIn field.
func (r *queryResolver) SignIn(ctx context.Context, input gql.SignInInput) (*gql.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}
