version: '3.8'
services:
  mysql:
    container_name: company-02
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - company_02_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: default_schema
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_TCP_PORT: 3401
    ports:
      - 3401:3401