version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGPORT: ${PORT}
      SSL_MODE: disable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}

volumes:
  postgres_data: