version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes: 
      - company2_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - ${PORT}:${PORT}

volumes:
  company2_data: